#include "fmod_core_module.h"

using namespace godot;

void FMODCoreModule::_bind_methods()
{
    // FMOD_MODE
    BIND_CONSTANT(FMOD_DEFAULT);
    BIND_CONSTANT(FMOD_LOOP_OFF);
    BIND_CONSTANT(FMOD_LOOP_NORMAL);
    BIND_CONSTANT(FMOD_LOOP_BIDI);
    BIND_CONSTANT(FMOD_2D);
    BIND_CONSTANT(FMOD_3D);
    BIND_CONSTANT(FMOD_CREATESTREAM);
    BIND_CONSTANT(FMOD_CREATESAMPLE);
    BIND_CONSTANT(FMOD_CREATECOMPRESSEDSAMPLE);
    BIND_CONSTANT(FMOD_OPENUSER);
    BIND_CONSTANT(FMOD_OPENMEMORY);
    BIND_CONSTANT(FMOD_OPENMEMORY_POINT);
    BIND_CONSTANT(FMOD_OPENRAW);
    BIND_CONSTANT(FMOD_OPENONLY);
    BIND_CONSTANT(FMOD_ACCURATETIME);
    BIND_CONSTANT(FMOD_MPEGSEARCH);
    BIND_CONSTANT(FMOD_NONBLOCKING);
    BIND_CONSTANT(FMOD_UNIQUE);
    BIND_CONSTANT(FMOD_3D_HEADRELATIVE);
    BIND_CONSTANT(FMOD_3D_WORLDRELATIVE);
    BIND_CONSTANT(FMOD_3D_INVERSEROLLOFF);
    BIND_CONSTANT(FMOD_3D_LINEARROLLOFF);
    BIND_CONSTANT(FMOD_3D_LINEARSQUAREROLLOFF);
    BIND_CONSTANT(FMOD_3D_INVERSETAPEREDROLLOFF);
    BIND_CONSTANT(FMOD_3D_CUSTOMROLLOFF);
    BIND_CONSTANT(FMOD_3D_IGNOREGEOMETRY);
    BIND_CONSTANT(FMOD_IGNORETAGS);
    BIND_CONSTANT(FMOD_LOWMEM);
    BIND_CONSTANT(FMOD_VIRTUAL_PLAYFROMSTART);

    // FMOD_TIMEUNIT
    BIND_CONSTANT(FMOD_TIMEUNIT_MS);
    BIND_CONSTANT(FMOD_TIMEUNIT_PCM);
    BIND_CONSTANT(FMOD_TIMEUNIT_PCMBYTES);
    BIND_CONSTANT(FMOD_TIMEUNIT_RAWBYTES);
    BIND_CONSTANT(FMOD_TIMEUNIT_PCMFRACTION);
    BIND_CONSTANT(FMOD_TIMEUNIT_MODORDER);
    BIND_CONSTANT(FMOD_TIMEUNIT_MODROW);
    BIND_CONSTANT(FMOD_TIMEUNIT_MODPATTERN);

    // FMOD_SOUND_TYPE
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_UNKNOWN);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_AIFF);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_ASF);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_DLS);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_FLAC);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_FSB);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_IT);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_MIDI);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_MOD);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_MPEG);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_OGGVORBIS);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_PLAYLIST);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_RAW);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_S3M);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_USER);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_WAV);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_XM);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_XMA);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_AUDIOQUEUE);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_AT9);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_VORBIS);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_MEDIA_FOUNDATION);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_MEDIACODEC);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_FADPCM);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_OPUS);
    BIND_ENUM_CONSTANT(FMOD_SOUND_TYPE_MAX);

    // FMOD_SOUND_FORMAT
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_NONE);
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_PCM8);
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_PCM16);
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_PCM24);
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_PCM32);
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_PCMFLOAT);
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_BITSTREAM);
    BIND_ENUM_CONSTANT(FMOD_SOUND_FORMAT_MAX); 

    // FMOD_CHANNELCONTROL_DSP_INDEX
    BIND_ENUM_CONSTANT(FMOD_CHANNELCONTROL_DSP_HEAD);
    BIND_ENUM_CONSTANT(FMOD_CHANNELCONTROL_DSP_FADER);
    BIND_ENUM_CONSTANT(FMOD_CHANNELCONTROL_DSP_TAIL);
}