#include "fmod_core_module.h"

using namespace godot;

void FMODCoreModule::_bind_methods()
{
    BIND_CONSTANT(FMOD_DEFAULT);
    BIND_CONSTANT(FMOD_LOOP_OFF);
    BIND_CONSTANT(FMOD_LOOP_NORMAL);
    BIND_CONSTANT(FMOD_LOOP_BIDI);
    BIND_CONSTANT(FMOD_2D);
    BIND_CONSTANT(FMOD_3D);
    BIND_CONSTANT(FMOD_CREATESTREAM);
    BIND_CONSTANT(FMOD_CREATESAMPLE);
    BIND_CONSTANT(FMOD_CREATECOMPRESSEDSAMPLE);
    BIND_CONSTANT(FMOD_OPENUSER);
    BIND_CONSTANT(FMOD_OPENMEMORY);
    BIND_CONSTANT(FMOD_OPENMEMORY_POINT);
    BIND_CONSTANT(FMOD_OPENRAW);
    BIND_CONSTANT(FMOD_OPENONLY);
    BIND_CONSTANT(FMOD_ACCURATETIME);
    BIND_CONSTANT(FMOD_MPEGSEARCH);
    BIND_CONSTANT(FMOD_NONBLOCKING);
    BIND_CONSTANT(FMOD_UNIQUE);
    BIND_CONSTANT(FMOD_3D_HEADRELATIVE);
    BIND_CONSTANT(FMOD_3D_WORLDRELATIVE);
    BIND_CONSTANT(FMOD_3D_INVERSEROLLOFF);
    BIND_CONSTANT(FMOD_3D_LINEARROLLOFF);
    BIND_CONSTANT(FMOD_3D_LINEARSQUAREROLLOFF);
    BIND_CONSTANT(FMOD_3D_INVERSETAPEREDROLLOFF);
    BIND_CONSTANT(FMOD_3D_CUSTOMROLLOFF);
    BIND_CONSTANT(FMOD_3D_IGNOREGEOMETRY);
    BIND_CONSTANT(FMOD_IGNORETAGS);
    BIND_CONSTANT(FMOD_LOWMEM);
    BIND_CONSTANT(FMOD_VIRTUAL_PLAYFROMSTART);

    BIND_CONSTANT(FMOD_TIMEUNIT_MS);
    BIND_CONSTANT(FMOD_TIMEUNIT_PCM);
    BIND_CONSTANT(FMOD_TIMEUNIT_PCMBYTES);
    BIND_CONSTANT(FMOD_TIMEUNIT_RAWBYTES);
    BIND_CONSTANT(FMOD_TIMEUNIT_PCMFRACTION);
    BIND_CONSTANT(FMOD_TIMEUNIT_MODORDER);
    BIND_CONSTANT(FMOD_TIMEUNIT_MODROW);
    BIND_CONSTANT(FMOD_TIMEUNIT_MODPATTERN);
}